cargo-features = ["edition2024"]

[package]
name = "keyrank-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "keyrank_rs"
crate-type = ["cdylib"]

[dependencies]
nalgebra = "0.33.2"
numpy = "0.25.0"


[dependencies.pyo3]
version = "0.25.0"
features = ["abi3-py38", "extension-module"]
